### ISSUE TITLE
Comparison with more popular libraries

### ISSUE THREAD

**Issue by dandv** [mljs/binary-search#2]
Same [question](https://github.com/amgadfahmi/js-binarysearch/issues/6) as for @amgadfahmi's module. Thanks!

**Comment by targos** [comment]
I don't remember what was the reason, but given that the [`binary-search`](https://github.com/darkskyapp/binary-search) package does exactly what I needed, I suppose I just forgot at that time to search on npm.
Perhaps I should deprecate this and redirect to the popular one, what do you think ?

**Comment by dandv** [comment]
> Perhaps I should deprecate this and redirect to the popular one, what do you think 

:+1: Wish way more package authors had this attitude.

**Comment by targos** [comment]
Done. Thanks for bringing this to our attention!
